services:
  - type: web
    name: dataentry-api
    runtime: docker
    dockerfilePath: ./DataEntry.Api/Dockerfile
    dockerContext: ./DataEntry.Api
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_HTTP_PORTS
        value: "8080"
      - key: Jwt__Key
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: Jwt__Issuer
        value: DataEntry.Api
      - key: Jwt__Audience
        value: DataEntry.UI
      - key: CORS_ORIGINS
        value: https://pitstop-detailing-studio-billbook-nolfcedah.vercel.app,https://pitstop-detailing-studio-billbook.vercel.app
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: dataentry-db
          property: connectionString

databases:
  - name: dataentry-db
    plan: free
